### PR TITLE
Split up monolithic binding module

### PR DESCRIPTION
**Pull request by mboes**
Upstream ships the API as a single gigantic header file. Since this is
a C API, there is no namespacing. That doesn't mean we need to do the
same. We instead design the bindings with the idea that modules will
be imported qualified by the user. This makes it easier to group
related functions together, it's easier to manage multiple smaller
modules rather than one large module, and we can shorten function names.

### CODE REVIEW

**Comment by mboes** [comment]
@TerrorJack conflict resolution with #1 lead to a subtle change. The `newtype` strategy for `Show` is only used for newtype `Index`, not any of the other newtypes.

**Comment by TerrorJack** [comment]
@mboes What do you think of having `Binaryen` or another module re-exporting all modules? Users (like us) won't need a long list of `import` clauses.

**Comment by mboes** [comment]
I think that's not technically feasible given the changes in this PR. Multiple functions in different modules can have the same name, like `Binaryen.Type.create` and `Binaryen.Module.create`. Nor desirable: since the modules are intendent to be imported qualified, no need for import lists. Although the type names could get annoying (e.g. `Binaryen.Module.Module`). So maybe we could reexport the type names in `Binaryen`?

**Comment by TerrorJack** [comment]
There are indeed a few top-level names (e.g. `create`) exported by different modules; now I think having a fat import list is a lesser evil, since renaming those things to something like `createModule` defeats the purpose of module splitting, and coming up with a list of non-conflicting names to export is troublesome.

**Review by TerrorJack — APPROVED** [review]

**Pull request merged**
